<?php
$a = '[{c:[{h:"07:00<br><span class=\"smaller soft\">Wed, 23 May<\/span>"},{s:"wt-ic",h:"<img class=mtt title=\"Overcast.\" src=\"\/\/c.tadst.com\/gfx\/w\/40\/wt-7.png\" width=40 height=40>"},{h:"26&nbsp;°C"},{s:"small",h:"Overcast."},{s:"sep",h:"No wind"},{h:"<span class=\"comp sa16\" title=\"Wind blowing from 0° North to South\">↑<\/span>"},{h:"91%"},{s:"sep",h:"1008 mbar"},{h:"10&nbsp;km"}]},{c:[{h:"10:00"},{s:"wt-ic",h:"<img class=mtt title=\"Partly sunny.\" src=\"\/\/c.tadst.com\/gfx\/w\/40\/wt-6.png\" width=40 height=40>"},{h:"32&nbsp;°C"},{s:"small",h:"Partly sunny."},{s:"sep",h:"No wind"},{h:"<span class=\"comp sa16\" title=\"Wind blowing from 0° North to South\">↑<\/span>"},{h:"71%"},{s:"sep",h:"1009 mbar"},{h:"10&nbsp;km"}]},{c:[{h:"13:00"},{s:"wt-ic",h:"<img class=mtt title=\"Partly sunny.\" src=\"\/\/c.tadst.com\/gfx\/w\/40\/wt-6.png\" width=40 height=40>"},{h:"34&nbsp;°C"},{s:"small",h:"Partly sunny."},{s:"sep",h:"4 km\/h"},{h:"<span class=\"comp sa26\" title=\"Wind blowing from 120° East-southeast to West-northwest\">↑<\/span>"},{h:"60%"},{s:"sep",h:"1006 mbar"},{h:"10&nbsp;km"}]},{c:[{h:"16:00"},{s:"wt-ic",h:"<img class=mtt title=\"Thunderstorms. Overcast.\" src=\"\/\/c.tadst.com\/gfx\/w\/40\/wt-22.png\" width=40 height=40>"},{h:"32&nbsp;°C"},{s:"small",h:"Thunderstorms. Overcast."},{s:"sep",h:"11 km\/h"},{h:"<span class=\"comp sa14\" title=\"Wind blowing from 330° North-northwest to South-southeast\">↑<\/span>"},{h:"69%"},{s:"sep",h:"1006 mbar"},{h:"10&nbsp;km"}]},{c:[{h:"19:00"},{s:"wt-ic",h:"<img class=mtt title=\"Light rain. Overcast.\" src=\"\/\/c.tadst.com\/gfx\/w\/40\/wt-34.png\" width=40 height=40>"},{h:"29&nbsp;°C"},{s:"small",h:"Light rain. Overcast."},{s:"sep",h:"No wind"},{h:"<span class=\"comp sa16\" title=\"Wind blowing from 0° North to South\">↑<\/span>"},{h:"83%"},{s:"sep",h:"1007 mbar"},{h:"8&nbsp;km"}]},{c:[{h:"22:00"},{s:"wt-ic",h:"<img class=mtt title=\"Overcast.\" src=\"\/\/c.tadst.com\/gfx\/w\/40\/wt-17.png\" width=40 height=40>"},{h:"28&nbsp;°C"},{s:"small",h:"Overcast."},{s:"sep",h:"No wind"},{h:"<span class=\"comp sa16\" title=\"Wind blowing from 0° North to South\">↑<\/span>"},{h:"81%"},{s:"sep",h:"1009 mbar"},{h:"10&nbsp;km"}]}]';
$a = preg_replace("/c\:/",'"c":',$a);
$a = preg_replace("/s\:/",'"s":',$a);
$a = preg_replace("/h\:/",'"h":',$a);
$a = preg_replace("/\&nbsp\;/",' ',$a);

echo $a . "\n";
$b = json_decode($a);
var_dump($b);

?>
